services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/principal/Dockerfile
    depends_on:
      - "external-api"
    ports:
      - "3001:3001"

  external-api:
    container_name: external-api
    build:
      context: .
      dockerfile: ./apps/external-api/Dockerfile
    depends_on:
      - "authentication-service"
    ports:
      - "3333:3333"

  authentication-service:
    container_name: authentication-service
    build:
      context: .
      dockerfile: ./apps/authentication-service/Dockerfile
    ports:
      - "3334:3334"
